<h4> Arange() Function </h4>

In [1]:
import numpy as np

In [2]:
print(help(np.arange))

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [3]:
# Start is inclusive, Stope is exclusive
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# The default value of start is 0
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
# start from 1, and step by 2 and end at 10 (excluding 10)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [6]:
np.arange(3.0)

array([0., 1., 2.])

In [7]:
np.arange(20, dtype="complex")

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [8]:
np.arange(1, 10, 2, dtype="float")

array([1., 3., 5., 7., 9.])